config_rewrite: replace
access_key: ''
secret_key: ''
use_instance_profile: false
credentials_file: ''
bucket: drupal
region: us-east-1
use_cname: true
use_customhost: true
hostname: 'minio:9000'
domain: minio.inno.cloud.statcan.ca/minio
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: false
redirect_styles_ttl: 0
no_rewrite_cssjs: false
root_folder: ''
public_folder: drupal-public
private_folder: drupal-private
presigned_urls: ''
saveas: ''
torrents: ''
